gh: use checkout to get the downloaded data
iterative/dvc-bench pull request #251
Opened 2021-04-23 12:09 UTC by isidentical

Now, instead of caching the `data/cats_dogs` it caches the `.dvc/cache`. Also in the later step it only fetches and for both cases, it uses `dvc checkout`.

2021-04-24 19:55 UTC, efiop commented
@isidentical Could you elaborate on reasoning, please?

2021-04-24 20:03 UTC, isidentical commented
> Could you elaborate on reasoning, please?

testing something now, though the current workflow doesn't actually put cached data into `.dvc/cache` but rather just moves it to `data/cats_dogs` which is not the correct behavior. using `checkout` and caching `.dvc/cache` instead will fix this though there is a weird thing that blocks me right now, trying to test it.

2021-04-25 22:20 UTC, pared commented
> > Could you elaborate on reasoning, please?
> 
> testing something now, though the current workflow doesn't actually put cached data into `.dvc/cache` but rather just moves it to `data/cats_dogs` which is not the correct behavior. using `checkout` and caching `.dvc/cache` instead will fix this though there is a weird thing that blocks me right now, trying to test it.

But in this change the caching has been removed completely, don't you want to cache the `.dvc/cache`?

2021-04-25 22:30 UTC, isidentical commented
> But in this change the caching has been removed completely, don't you want to cache the .dvc/cache?

No, I was testing something. Will send to normal patch on monday

2021-04-30 12:18 UTC, isidentical commented
The cache is working fine for linux/macos though on windows there seems to be an error :eyes: I have no idea about why, though maybe we could just disable it on windows (cc: @pared)

2021-04-30 16:37 UTC, pared commented
@isidentical I think it might have something to do with the paths. Looking into logs, it seems like even on windows paths are provided with slashes (`C:\Windows\System32\tar.exe -z -xf D:/a/_temp/0aa681e6-55b2-4c37-a87f-dea8d0303fec/cache.tgz -P -C D:/a/dvc-bench/dvc-bench`) can't say for sure what is happening. I don't think we should be removing that. Windows and macOS builds are done to make sure we are not supporting only single system. (Even though we do not run full benchmarks on macOs and Win, we would like to get back to that at some point). 

Shouldn't pull handle existing cache? Maybe we could replace `fetch/checkout` with `pull` and cache only for macOs and Linux, and continue with investigation on windows later?

2021-05-03 09:21 UTC, isidentical commented
@pared went that way!

2021-05-03 11:47 UTC, pared approved these changes

2021-05-03 11:51 UTC, pared requested changes

2021-05-03 11:51 UTC, pared commented on .github/workflows/pull_request_build.yml
> +      - name: checkout data
Name is not adequate to what this step is doing.
Also, now I wonder whether we need fetch step at all? If we restored the cache, what `pull` should be doing is only repopulating state, right? Maybe we just need to keep the `pull` step?

2021-05-03 11:51 UTC, pared commented on .github/workflows/pull_request_build.yml
> +          key: ${{ runner.os }}-data-${{ hashFiles('**/*.dvc') }}
I would put here an if checking the system - now, on windows we will get additional work done

2021-05-03 13:05 UTC, pared approved these changes
One minor thingy

2021-05-03 13:05 UTC, pared commented on .github/workflows/pull_request_build.yml
> +      - name: checkout data
`pull` data :)

2021-05-03 13:12 UTC, isidentical commented on .github/workflows/pull_request_build.yml
> +      - name: checkout data
```suggestion
      - name: pull data
 ```

2021-05-03 13:36 UTC, pared approved these changes

2021-05-03 13:39 UTC, merged